postConditilonHandlerの修正
traP-jp/yaranai-backend pull request #13
Opened 2023-12-13 15:35 UTC by alter334

元のブランチがdelete等混在し分かりづらくなったためPOST部分のみ別ブランチを生やした

2023-12-14 07:37 UTC, ramdos0207 requested changes

2023-12-14 07:37 UTC, ramdos0207 commented on src/condition.go
> +	var conditions []Condition
openAPIではuserを返さないことになっているので、これを抜いて返してほしいです

2023-12-14 15:04 UTC, alter334 commented on src/condition.go
> +	var conditions []Condition
修正コミットしました
deleteHandlerでも同様の実装となっていたためUserを返さないよう変更しています

2023-12-14 15:25 UTC, alter334 commented
## PUT: /condition
- レスポンスを受け取る部分はpostConditionHandler,パスパラメータの受け取りとレスポンスはdeleteConditionHandlerに準じた

2023-12-15 02:47 UTC, Pugma reviewed
とりあえず、旗から首突っ込んでみて気づいたことを色々書いてみた

2023-12-15 02:47 UTC, Pugma commented on src/condition.go
> +		fmt.Println(err)
チョー細かいところなんだけど、
当たられたcondition_idのものが存在するかの確認を実施してるから、見つからなかったときに
`internal server error`
はちょっとおかしいかも…？

2023-12-15 02:47 UTC, Pugma commented on src/condition.go
> +	}
ここのチェックって、
`condition_id`かつ`userId`が両方DBないと一致するやつだけselectしてくるってことをやってみるともしかしたら1つのSQL文まとめて処理できるかも…？

2023-12-15 02:47 UTC, Pugma commented on src/condition.go
> +		return c.String(http.StatusForbidden, "Forbidden")
ここも上記と同じようにできるかも

2023-12-15 02:47 UTC, Pugma commented on src/model.go
> +}
ここのomitEmptyはプロジェクトで見た覚えのない実装なのでちょっと不安かもです
一応本当に必要な記述かチェックしてみてほしいかも

2023-12-15 03:20 UTC, alter334 commented on src/condition.go
> +	}
すでに実装されているdeleteTaskの方がhttp.StatusUnauthorizedで非許可みたいに実装していたりするので許可されてない状況出すためにもこの部分は独立して存在した方がいいかなと思った(ステータスやメッセージはtask側に合わせて修正しておきます)

2023-12-15 03:22 UTC, alter334 commented on src/model.go
> +}
Userのomitemptyはユーザー名をレスポンスに含まないようにするため(.User="" をしている)に実装
Nameのomitemptyは確かに要らない実装です(空文字判定するときに試行錯誤した跡です)

レスポンスように新しく構造体を定義すればどちらのomitemptyも取っ払える感じです

2023-12-15 03:23 UTC, alter334 commented on src/condition.go
> +		fmt.Println(err)
`404 NotFound`
に修正しました

2023-12-15 03:52 UTC, alter334 commented on src/model.go
> +}
割と重大な実装ミスが見つかりました
レスポンス用の構造体がやはり必要っぽいです

2023-12-15 05:12 UTC, alter334 commented
↑
この修正の動作を確認しました

2023-12-15 05:17 UTC, ramdos0207 commented on src/condition.go
> +	}
挙動が変わるのでまとめられるからという理由で変更するとまずいのですが、他人のタスクの存在判定が出来ちゃうのはそれはそれでまずい気もしています

2023-12-15 06:04 UTC, ramdos0207 approved these changes

2023-12-15 06:04 UTC, ramdos0207 commented
マージしてください！

2023-12-15 06:06 UTC, merged